import inspect
from pathlib import Path
from typing import List, Dict, Any, Optional
from .inspector import DotNetInspector
from .exceptions import NotDotNetAssemblyError

class WrapperGenerator:
    """
    Generates Python wrapper modules for .NET assemblies.
    """
    
    def __init__(self, dll_path: str):
        self.inspector = DotNetInspector(dll_path)
        self.assembly_name = self.inspector.assembly.GetName().Name
    
    def generate_wrapper(self, output_path: Optional[str] = None) -> str:
        """
        Generate a complete Python wrapper module.
        
        Args:
            output_path: Where to save the wrapper (optional)
            
        Returns:
            Generated wrapper code as string
        """
        lines = []
        
        # Header and imports
        lines.extend(self._generate_header())
        lines.append("")
        
        # Assembly loading
        lines.extend(self._generate_loader())
        lines.append("")
        
        # Generate classes
        for class_info in self.inspector.get_classes():
            lines.extend(self._generate_class_wrapper(class_info))
            lines.append("")
        
        wrapper_code = "\n".join(lines)
        
        if output_path:
            Path(output_path).write_text(wrapper_code, encoding='utf-8')
        
        return wrapper_code
    
    def _generate_header(self) -> List[str]:
        """Generate module header with docstring."""
        header = [
            '"""',
            f'Python wrapper for .NET assembly: {self.assembly_name}',
            '',
            'Auto-generated by py-dotnet-importer',
            '"""',
            '',
            'import clr',
            'from typing import Any, List, Dict, Optional, Union, Tuple',
            'from datetime import datetime',
            '',
        ]
        return header
    
    def _generate_loader(self) -> List[str]:
        """Generate assembly loading code."""
        dll_path = self.inspector.dll_path
        return [
            f'# Load .NET assembly',
            f'clr.AddReference(r"{dll_path}")',
            f'from {self.assembly_name} import *',
            '',
            f'__all__ = []  # Will be populated with class names',
        ]
    
    def _generate_class_wrapper(self, class_info: Dict[str, Any]) -> List[str]:
        """Generate wrapper for a single class."""
        lines = []
        class_name = class_info["full_name"]
        safe_name = class_info["name"]
        
        # Class docstring
        lines.append(f'class {safe_name}:')
        lines.append(f'    """')
        lines.append(f'    Wrapper for .NET class: {class_name}')
        lines.append(f'    Namespace: {class_info["namespace"]}')
        lines.append(f'    Base type: {class_info["base_type"]}')
        lines.append(f'    """')
        lines.append('')
        
        # Import the underlying .NET type
        lines.append(f'    _dotnet_type = __import__("{self.assembly_name}").{safe_name}')
        lines.append('')
        
        # Constructor
        lines.extend(self._generate_constructor(class_info))
        lines.append('')
        
        # Properties
        for prop in class_info.get("properties", []):
            lines.extend(self._generate_property(prop))
        
        # Methods
        for method in class_info.get("methods", []):
            lines.extend(self._generate_method(method))
        
        lines.append('')
        lines.append(f'__all__.append("{safe_name}")')
        
        return lines
    
    def _generate_constructor(self, class_info: Dict[str, Any]) -> List[str]:
        """Generate __init__ method."""
        lines = []
        ctors = class_info.get("constructors", [])
        
        if not ctors:
            lines.append('    def __init__(self):')
            lines.append('        self._instance = self._dotnet_type()')
            return lines
        
        # Use first constructor for signature
        ctor = ctors[0]
        params = ctor.get("parameters", [])
        
        # Build parameter string
        param_strs = []
        for p in params:
            param_type = self._map_dotnet_type(p["type"])
            param_strs.append(f'{p["name"]}: {param_type}')
        
        sig = ", ".join(param_strs)
        if sig:
            sig = ", " + sig
        
        lines.append(f'    def __init__(self{sig}):')
        lines.append('        """Initialize the .NET object."""')
        
        # Build argument forwarding
        args = ", ".join([p["name"] for p in params])
        lines.append(f'        self._instance = self._dotnet_type({args})')
        
        return lines
    
    def _generate_method(self, method_info: Dict[str, Any]) -> List[str]:
        """Generate wrapper for a method."""
        lines = []
        method_name = method_info["name"]
        
        # Skip if it's a special method
        if method_name.startswith('get_') or method_name.startswith('set_'):
            return []
        
        # Build signature
        params = method_info.get("parameters", [])
        param_strs = []
        for p in params:
            param_type = self._map_dotnet_type(p["type"])
            default = ""
            if p.get("is_optional"):
                default_val = p.get("default_value")
                if default_val is not None:
                    default = f" = {repr(default_val)}"
                else:
                    default = " = None"
            param_strs.append(f'{p["name"]}: {param_type}{default}')
        
        sig = ", ".join(param_strs)
        if sig:
            sig = ", " + sig
        
        # Return type
        return_type = self._map_dotnet_type(method_info["return_type"])
        
        # Method definition
        decorator = '@staticmethod' if method_info.get("is_static") else ''
        if decorator:
            lines.append(f'    {decorator}')
        
        self_param = '' if method_info.get("is_static") else 'self'
        if self_param and sig:
            sig = self_param + sig
        elif self_param:
            sig = self_param
        
        lines.append(f'    def {method_name}({sig}) -> {return_type}:')
        
        # Docstring
        lines.append('        """')
        lines.append(f'        {method_name}')
        lines.append('')
        if params:
            lines.append('        Args:')
            for p in params:
                lines.append(f'            {p["name"]}: {p["type"]}')
        lines.append(f'        Returns: {method_info["return_type"]}')
        lines.append('        """')
        
        # Implementation
        args = ", ".join([p["name"] for p in params])
        target = "self._instance" if not method_info.get("is_static") else "self._dotnet_type"
        lines.append(f'        return {target}.{method_name}({args})')
        
        return lines
    
    def _generate_property(self, prop_info: Dict[str, Any]) -> List[str]:
        """Generate property wrapper."""
        lines = []
        prop_name = prop_info["name"]
        prop_type = self._map_dotnet_type(prop_info["type"])
        
        # Getter
        if prop_info.get("can_read"):
            lines.append(f'    @property')
            lines.append(f'    def {prop_name}(self) -> {prop_type}:')
            lines.append(f'        """Get {prop_name}."""')
            lines.append(f'        return self._instance.{prop_name}')
        
        # Setter
        if prop_info.get("can_write"):
            lines.append(f'    @{prop_name}.setter')
            lines.append(f'    def {prop_name}(self, value: {prop_type}):')
            lines.append(f'        """Set {prop_name}."""')
            lines.append(f'        self._instance.{prop_name} = value')
        
        return lines
    
    def _map_dotnet_type(self, dotnet_type: str) -> str:
        """Map .NET types to Python type hints."""
        type_map = {
            'System.String': 'str',
            'System.Int32': 'int',
            'System.Int64': 'int',
            'System.Double': 'float',
            'System.Single': 'float',
            'System.Boolean': 'bool',
            'System.DateTime': 'datetime',
            'System.Object': 'Any',
            'System.Void': 'None',
            'System.Byte[]': 'bytes',
            'System.Array': 'List[Any]',
            'System.Collections.Generic.List`1': 'List',
            'System.Collections.Generic.Dictionary`2': 'Dict',
        }
        
        # Check exact match
        if dotnet_type in type_map:
            return type_map[dotnet_type]
        
        # Check generic types
        if '[]' in dotnet_type:
            return 'List[Any]'
        if 'System.Nullable`1' in dotnet_type:
            inner = dotnet_type.split('[')[1].rstrip(']')
            return f'Optional[{self._map_dotnet_type(inner)}]'
        
        # Default to Any for unknown types
        return 'Any'
